<?php
/** @var $this \Slim\Views\PhpRenderer */
/** @var $links string[] */
/** @var $actions string[] */
/** @var $parent ?string */
?>
<h1>
    Happy Horizon Patches
</h1>
    <?php if (empty($links)): ?>
        <span>No patches yet</span>
        <br/>
    <?php endif; ?>
<?php if (isset($parent)): ?>
<a href="<?= $parent?>">Go Back</a>
<?php endif; ?>
<ul>
    <?php foreach ($links as $link => $title): ?>
        <li>
            <a href="<?= $link ?>"><?= $title ?></a>
        </li>
    <?php endforeach; ?>
</ul>

<?php if (!empty($actions)): ?>
    <?php foreach ($actions as $link => $title): ?>
        <button>
            <a href="<?= $link ?>"><?= $title ?></a>
        </button>
    <?php endforeach; ?>
<?php endif; ?>